# Generated by Django 5.0.14 on 2026-09-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation / Payment'), ('CONFIRMED', 'Confirmed & Scheduled'), ('COMPLETED', 'Session Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined by Tutor')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=150)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
