# Generated by Django 5.0.14 on 2026-09-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('booking_request', 'New Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('review_request', 'Review Request'), ('general', 'General Notification')], default='general', max_length=30)),
                ('action_url', models.CharField(blank=True, default='/dashboard', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
