# Generated by Django 5.0.14 on 2026-09-05 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='Leave blank if all-day block', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Leave blank if all-day block', null=True)),
                ('all_day', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='', max_length=160)),
                ('bio', models.TextField(blank=True, default='')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=45.0, max_digits=8, validators=[django.core.validators.MinValueValidator(5.0)])),
                ('rating_avg', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, default='San Francisco', max_length=100)),
                ('state', models.CharField(blank=True, default='CA', max_length=50)),
                ('country', models.CharField(blank=True, default='USA', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('travel_radius_km', models.PositiveIntegerField(default=25, help_text='Service radius in kilometers')),
                ('offers_online', models.BooleanField(default=True)),
                ('offers_in_person', models.BooleanField(default=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of subjects/skills strings')),
                ('languages', models.JSONField(blank=True, default=list, help_text='Languages spoken')),
                ('portfolio_images', models.JSONField(blank=True, default=list, help_text='List of image URLs or badges')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating_avg', '-reviews_count'],
            },
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mathematics', 'Mathematics & Statistics'), ('computer_science', 'Computer Science & Coding'), ('sciences', 'Physics, Chemistry & Biology'), ('languages', 'Languages & Literature'), ('music', 'Music & Instruments'), ('test_prep', 'SAT, ACT & Standardized Tests'), ('business', 'Business, Economics & Finance'), ('other', 'Other Specialized Skills')], default='mathematics', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(5.0)])),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes (e.g. 60, 90)')),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
