# Generated by Django 5.0.14 on 2026-09-05 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='providers.providerprofile'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['rating_avg', 'reviews_count'], name='providers_p_rating__a5ec0d_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['city', 'is_active'], name='providers_p_city_f52f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['hourly_rate'], name='providers_p_hourly__c2d90e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('provider', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category', 'is_paused'], name='providers_s_categor_3566cc_idx'),
        ),
    ]
