# Generated by Django 5.0.14 on 2026-09-05 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='providers.providerprofile'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['provider', 'rating'], name='reviews_rev_provide_1fa2e2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['client'], name='reviews_rev_client__578445_idx'),
        ),
    ]
